disabled_rules:
  - file_length
  - type_body_length
  - function_body_length
  - line_length
  - identifier_name
  - trailing_comma
  - implicit_optional_initialization
  - opening_brace
  - nesting
  - for_where
  - static_over_final_class

excluded:
  - .git
  - .cursor
  - DerivedData
